### ISSUE TITLE
lettermgmt: semantics of send_id, recipient_ids, partner_id, extern_partner_ids

### ISSUE THREAD

**Issue by hbrunn** [OCA/crm#10]
@bwrsandman,

I'm now busy porting lettermgmt to 8.0 and I'm a bit confused about the semantics of the fields mentioned above. In 6.0, there was snd_rec_id and partner_id which was respectively the user who sent a letter and the partner to receive it if it's an outgoing letter, while snd_rec_id was the addressee and partner_id the sender if it's an incoming letter.

Now in 7.0, the incoming letter form gives me partner_id as recipient and send_id as sender. I don't understand the reasoning here, shouldn't it be the other way around, that I send something to a partner and the sender necessarily is a user?

Then for outgoing letters, we have recipient_ids (which refers to res.users) as recipients and no sender. There's also extern_partner_ids what I would have expected as the recipients field.

What do I misunderstand here?

**Comment by bwrsandman** [comment]
It's probably a mistake on my part. We ended up not using `lettermgmt`.

It's been a while since I touched `lettermgmt`, it might not have fully been ported.

**Comment by hbrunn** [comment]
thanks @bwrsandman, so if I PR some changes to 7.0 following the lines above you wouldn't mind?

**Comment by bwrsandman** [comment]
Go for it!

**Comment by pedrobaeza** [comment]
Can this be closed?

**Comment by hbrunn** [comment]
yes
