### ISSUE TITLE
8.0 - mass_mailing_partner : only selected partners are moved in mailing list

### ISSUE THREAD

**Issue by mamaf** [OCA/crm#124]
Hi,

When selecting a list of partners to add to a mailing list, defining search criteria and clicking on top selection checkbox, only the partners selected in the first page (80 by default) are selected.
It's not possible to select all partners matching search criteria, unless displaying all lines in the list, which could be difficult for a large selection.
Is it "normal" ?

**Comment by pedrobaeza** [comment]
Change the limit of the pager to "Unlimited".

**Comment by mamaf** [comment]
I tried this but I have more than 10.000 contacts in this list, it's very long to get an answer

And also, when we have duplicates in emails, the process stops
Is there a version of this module that could pass through duplicates (simply not creating them in the mailing list) ?

**Comment by pedrobaeza** [comment]
It's the only way right now. Last version prevents duplicates.

**Comment by rafaelbn** [comment]
Hi, I guess you load one time the 10K customers (res.parnets) to the list, isn't it? or do you load / update it recurring?

**Comment by mamaf** [comment]
@pedrobaeza indeed, the last version accepts duplicates, but does it remove duplicates ?

@rafaelbn Yes, in one shot
But of course, I have a timeout
Can we update the list in a recurring way ?

**Comment by pedrobaeza** [comment]
If I don't remember bad, there's a list at the end of the process that says that you have a duplicated partner or email, but I'm not sure about the second one. 

You can fill your list by parts, of course.

**Comment by rafaelbn** [comment]
As I remember, module don't import Partners with duplicate email address.

@mamaf 
- if is one shoot then I recommend to add Partners to the list by 500 shot (you need 20 shots but It will work)
- If you need to update list " Can we update the list in a recurring way ?" the it's needed a development. We had an approach of what it must be done but by the moment no customer which pay it. The idea is to have in list a filter from partners so then list will be automatically update on real-time.

**Comment by mamaf** [comment]
OK, I tested on a small list, the duplicates are not created, without error message, which is OK for me
For the user point of view, we cannot ask him to cut his list in packs of 500 or even 1000, it's time consuming, and the list will not be updated thereafter ...
Thanks for your answers, @pedrobaeza and @rafaelbn

**Comment by rafaelbn** [comment]
@mamaf Take a look in https://github.com/OCA/social/tree/8.0/mass_mailing_unique

**Comment by mamaf** [comment]
I already looked at it  ;-)
But it simply raises errors when duplicates : that's not what I want
But the actual Functioning of last version of mass_mailing_partner is OK for me (only the problem of big lists that could raise a timeout)
