### ISSUE TITLE
what about writing a letter with this module

### ISSUE THREAD

**Issue by berctain** [OCA/crm#139]
Hi
so i would say what about writing a letter with this module instead with only tracking physical letters and parcels?!
since its an erp system so this not look fine to typing a letter with office software's and booking it manually then just tracking that in erp solutions, it would be great to typing letter inside of this module and get a serial number for tracking wokflow and entering physcal letters in same time with same systems too
:)

**Comment by pedrobaeza** [comment]
Which module? I don't understand what do you want to say. Is there any problem? Is this a wishlist?

**Comment by berctain** [comment]
lettermgmt module, actually its a wishlist for me, but about module its not much far feature in same time
