### ISSUE TITLE
[RFC] Change visualization of crm.lead depending on the type

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/crm#141]
Affected versions: 9.0, 10.0

Current situation:
When user belongs to group crm.group_use_lead (config option 'Use leads if you need a qualification step before creating an opportunity or a customer'). if you open an opportunity from a URL, such as http://3290757-10-0-453fe4.runbot2.odoo-community.org/web?reload#id=5&view_type=form&model=crm.lead, it displays as if it was a lead:

![image](https://cloud.githubusercontent.com/assets/7683926/25767511/3f4889f2-31fa-11e7-9e7a-aaa882a2af79.png)

However, this is not a lead! It does not say otherwise in the form view. 

However it is not listed anymore under 'Leads', but under 'Opportunities':
![image](https://cloud.githubusercontent.com/assets/7683926/25767526/6be9593c-31fa-11e7-85d0-fbccf4fd46b6.png)

The opportunity view is different from the lead view.

Perhaps in case the view to be represented should depend on the type (lead/opportunity)?

**Comment by JordiBForgeFlow** [comment]
@darshan-serpent what do you think about this?

**Comment by serpentcs-dev1** [comment]
I checked the link, yes you are right it is an Opportunity and it opens as a lead, strange!

Although I checked on other runbot instance I guess it worked fine there. Please check Opportunity on this URL: http://226032-10-0-6921da.runbot10.odoo.com/web?debug=1#id=22&view_type=form&model=crm.lead&menu_id=371&action=500

edit : Yeah it will only work if you pass the action in the link
