### ISSUE TITLE
How can I push?

### ISSUE THREAD

**Issue by eqms** [OCA/crm#181]
Hi,

how can I push changes(translations) or I just migrate crm_action from 8.0 to 10.0
I am already member of the OCA and listed as member in the OCA repository.

I want also help to migrate to 11.0 in different repositories?

**Comment by elicoidal** [comment]
@eqms  Thanks for your interest to the OCA. 
Let me introduce to you some basic information about contribution in OCA. 

In practice, to get started you should:
* check the issue related to migration in the repo to check nobody is already migrating the module you plan to
* fork the main repository into your user
* apply the changes (migration, new module, correction)
* propose a PR back to the main repository
* Ping the main contributor of the repo for review (to be noted that reviewers are scarce and you increase your chances of getting reviewed if you review yourself PR) 

In general, please follow the principles: 
* Contribution guidelines: https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md
* Please follow the OCA README template:
https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
* Please use simple headers in all py files following OCA templates
https://github.com/OCA/maintainer-tools/blob/master/template/module/__openerp__.py#L3

For the translation we are currently in a bit of transitioning from old platform (www.transifex.com) to the new one (https://translation.odoo-community.org/):
* You need to login (for example via github)
* Add languages and projects in the preferences
* Start translating
* Your translation will be updated every week to github

**Comment by elicoidal** [comment]
One last thing: you need to sign a Contributor License Agreement for the code you submit. More information here: https://odoo-community.org/page/cla

I will close this issue but do not hesitate to reopen it if you have more questions
