### ISSUE TITLE
[BUG] CRM menu is not loaded at all

### ISSUE THREAD

**Issue by melroy89** [OCA/crm#191]
Hi,

Impacted version: 11

The CRM module menu items stay hidden. Even though I have access to this menu, the permissions are correct.

The URL of Customer relation (CRM) ends with: `web#menu_id=215&action=315`. The `menu_d` 215  (`data-menu-parent="215"`) is present in the HTML contents.

As I said earlier the URL is `web#menu_id=215&action=315`, the `action` will (315, whatever that is?), will cause the menu_id disappearing from the URL. Without action filled in in the URL the menu does appear correctly.

To put it simple, the `action` will cause the menu not being displayed, the menu_id will get removed from the URL because of the action parameter is filled-in.

HOWEVER, in other modules, the action will not prevent the menu from being loaded.

I don't see any javascript error.

You can see it yourself at: http://erp.melroy.org/.
You can use 'demo' / 'demo' on the testing database. Which has the correct rights.

Thanks in advance.

Kind regards,
Melroy van den Berg

**Comment by melroy89** [comment]
I think I need to go to odoo/odoo github.

**Comment by melroy89** [comment]
Actually it's related to my theme (backend_theme): https://github.com/Openworx/backend_theme/issues/43

**Comment by mgielissen** [comment]
The code for the sidebar is the same as for v10. In v11 it seems the previous topmenu is shown sometimes.

**Comment by melroy89** [comment]
@mgielissen 
In v11 the *previous* topmenu is shown **always** whever you click on the **CRM** module using the backend_theme atleast. So whenever I click on an item before the CRM (doesn't matter which app), it will load that menu and stays at that menu. When I click on CRM, the CRM menu will not be loaded.

In fact if you use the website app (to design your own site), and then go directly to CRM. The menu area will stay blanco:
![image](https://user-images.githubusercontent.com/628926/35001818-fe43edc2-fae7-11e7-9009-0b76a9d1bbf1.png)


ps. not only the menu items doesn't appear, also the content text in the menu (saying 'CRM' or 'relationship management' or whatever language you installed) is missing as well or doesn't get loaded.

But look at the other issue on the backend_theme:
https://github.com/Openworx/backend_theme/issues/43

Since removing this theme will solve the problem.
