### ISSUE TITLE
How

### ISSUE THREAD

**Issue by axeforeverjumo** [OCA/crm#192]
I dont know how to install this in my Odoo, first at all I am using Odoo 11, and when I tried to install CRM Phonecalls, I have an Error.

> > Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/http.py", line 647, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo/http.py", line 307, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo/odoo/http.py", line 689, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo/http.py", line 339, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/odoo/http.py", line 332, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo/http.py", line 933, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo/http.py", line 512, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/addons/web/controllers/main.py", line 934, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/opt/odoo/addons/web/controllers/main.py", line 922, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-40>", line 2, in button_immediate_install
>   File "/opt/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/opt/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
>     return self._button_immediate_function(type(self).button_install)
>   File "/opt/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/opt/odoo/odoo/modules/registry.py", line 85, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/opt/odoo/odoo/modules/loading.py", line 343, in load_modules
>     loaded_modules, update_module)
>   File "/opt/odoo/odoo/modules/loading.py", line 242, in load_marked_modules
>     loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
>   File "/opt/odoo/odoo/modules/loading.py", line 135, in load_module_graph
>     registry.init_models(cr, model_names, {'module': package.name})
>   File "/opt/odoo/odoo/modules/registry.py", line 307, in init_models
>     model.init()
> TypeError: init() missing 1 required positional argument: 'cr'

**Comment by yajo** [comment]
Make sure your addon version matches your odoo version
