### ISSUE TITLE
runbot test: - does not prevent for double booking

### ISSUE THREAD

**Issue by clxadmin** [OCA/crm#203]
I've just testet this module on runbot and it does not prevent for double booking any resource even if 'allow double booking' is disabled

does someone have the same experience on runbot?

**Comment by pedrobaeza** [comment]
Which module? Which version?

**Comment by clxadmin** [comment]
https://github.com/OCA/crm/tree/10.0/calendar_resource  branch: [10]

Runbot: https://runbot.odoo-community.org/runbot/111/10.0

**Comment by pedrobaeza** [comment]
And why is going to prevent that? That's not a covered feature AFAIK

**Comment by clxadmin** [comment]
I might do not understand the final goal of this module. I thought this module is about 'ressource reservation (example: meeting room) to a meeting in calendar. This is also what the feature listing is saiing about:
_>> This module can also prevent resources from being double-booked. Go to a resource and disable or enable Allow Double Booking (this is disabled by default)._

So I created a meeting with same resource on same time/day with two different users  --- and it is not blocking the second meeting. So this ressource is double booked. Maybe I'm doing wrong and someone can guide me to the right point.
