### ISSUE TITLE
Server error when merging partner if an abstract model has a reference field in the registry

### ISSUE THREAD

**Issue by alv97** [OCA/crm#215]
**Impacted versions**: v8

**Steps to reproduce:**
have an abstract model with a reference field

**Current behavior:**
SQL exception (search on non existing table due to the abstract nature of the model)

**Screenshots:**

First select the contacts to merge like this:

![errormergeclient](https://user-images.githubusercontent.com/15813990/42809930-ffa98ace-89b6-11e8-95a0-b8feb2cc86d9.png)

after that just push on "Comprobar selección" or "comprobate selection"
and they will give us this message error:

![errormerge](https://user-images.githubusercontent.com/15813990/42809950-0cc650f2-89b7-11e8-81a4-47b88a789280.png)

**this issue was fixed on v9,v10 and v11 here** : 

https://github.com/odoo/odoo/issues/21137
https://github.com/odoo/odoo/issues/20210

**the solution for fix it is put this check:**

```
if not proxy_model._auto:
     continue
```

**Comment by pedrobaeza** [comment]
Which module? Can you make the PR?
