### ISSUE TITLE
crm_phonecall_summary_predefined breaks crm_phonecall_timesheet

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/crm#235]
This happens when creating a phone call from the "Logged Calls" Menu.
Error : a mandatory field is required: name. (but not name in the phone call, name in the analytic line)

crm_phonecall_timesheet creates an analytic line from the phonecall.
In the analytic line, the field 'name' is mandatory.
in the crm_phonecall_summary_predefined module, the name is replaced by the name related to the summary_id.name (see [here](https://github.com/OCA/crm/blob/11.0/crm_phonecall_summary_predefined/models/crm_phonecall.py)).
But as in the crm_phonecall_timesheet create method, it creates first the analytic line and then creates the phonecall, at the time the analytic line is created, the name has still not be set. (see [here](https://github.com/OCA/hr-timesheet/blob/10.0/crm_phonecall_timesheet/models/crm_phonecall.py) for the code)
The solution would be to leave the field 'name' as is (char field) and change its value in a @api.onchange(summary_id) method. I think it's even better because the user can still set its own name if he wants to.

**Comment by pedrobaeza** [comment]
The idea of the module is to not allow free texts, but for solving the problem, you only need to add the same onchange you are telling to add.

**Comment by Martronic-SA** [comment]
@pedrobaeza Unfortunately only the onchange method id not helping.
If you look [here](https://github.com/OCA/hr-timesheet/blob/10.0/crm_phonecall_timesheet/models/crm_phonecall.py#L39) as long as 'name' is readonly field, it's not passed to the vals and it's still not set in "self" (because the analytic line creation takes place before the phonecall creation), so 'name' is False

**Comment by pedrobaeza** [comment]
Which version?

**Comment by Martronic-SA** [comment]
v10.0

**Comment by pedrobaeza** [comment]
On that version we can't use a trick... then what I'm thinking is to add manually the value of name in vals dictionary in create/write before calling super.
