### ISSUE TITLE
crm_phonecall_summary_predefined breaks crm.phonecall2phonecall wizard

### ISSUE THREAD

**Issue by Martronic-SA** [OCA/crm#236]
summary_id field is missing in the phonecall2phonecall wizard.
As the summary_id is mandatory and not set through the wizard, it returns a mandatory field error.
see the code [here](https://github.com/OCA/crm/blob/11.0/crm_phonecall/wizard/crm_phonecall_to_phonecall.py#L54)

**Comment by pedrobaeza** [comment]
Please add that value in the wizard in a PR.

**Comment by Martronic-SA** [comment]
@pedrobaeza unfortunately the action_schedule method [here](https://github.com/OCA/crm/blob/11.0/crm_phonecall/wizard/crm_phonecall_to_phonecall.py#L54) has to be overridden 
and the same for schedule_another_phonecall method [here](https://github.com/OCA/crm/blob/11.0/crm_phonecall/models/crm_phonecall.py#L137) as it doesnt accept extra parameters (getting the new phonecall values shoud be in a separate extandable method)

**Comment by pedrobaeza** [comment]
I think you can tweak it passing by context the value and overwriting create method for adding that value in the context.
