### ISSUE TITLE
Calendar Resources - Show Resource's Calendar

### ISSUE THREAD

**Issue by Highcooley** [OCA/crm#237]
How is it possible for the calendar users to see the resource's calendar in order to check, when a certain resource is available without trial and error to book it.

**Comment by pedrobaeza** [comment]
Sorry, this is not an issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo-community.org/groups), but not here.

Closing this by the reason above.
