### ISSUE TITLE
Adding a Parent-Child hierarchy on Sales Teams

### ISSUE THREAD

**Issue by gva-acsone** [OCA/crm#241]
Hello,

I'm actually missing a notion to indicate that a Sales Team is part of another Sales Team (ex: Sales Team Berlin is part of Sales Team Germany).
Therefore, we would like to add a 'Parent' field on the Sales Team form. It can afterwards be used in the reports to look at the pipeline / sales at parent level...

@qgroulard will make a pull request for this.

**Comment by sbidoul** [comment]
Module name suggestion: `crm_team_parent`

**Comment by sbidoul** [comment]
Done in #244
