### ISSUE TITLE
[11.0] crm_phonecall error on "Schedule Another Call"

### ISSUE THREAD

**Issue by anandkansagra** [OCA/crm#248]
There seems an error while `Schedule Another Call` from `CRM -> Phone Calls -> Logged Calls`
![1](https://user-images.githubusercontent.com/45279628/49326701-3cd2d500-f57c-11e8-8511-b16e9cfb877f.gif)

**Comment by pedrobaeza** [comment]
Duplicate of #236

**Comment by pedrobaeza** [comment]
It seems not duplicate it at all, so I reopen.

**Comment by anandkansagra** [comment]
> It seems not duplicate it at all, so I reopen.

@pedrobaeza ,
I have fixed this thing in code migration in `12.0` 
PR [Reference](https://github.com/OCA/crm/pull/247)
