### ISSUE TITLE
install fail on odoo v12 CE

### ISSUE THREAD

**Issue by sync700uk** [OCA/crm#262]
Will not install on above version. Throws an exception stating that no such module is found. Script refers seems to v12 not v12.0.1.0.0 so install cannot find the module even though it is in the add-on folder

**Comment by pedrobaeza** [comment]
Which module?

**Comment by sync700uk** [comment]
Hi

CRM phonecall

Adrian Maudsley, MAAT

This email is strictly confidential and for the intended recipients only.
If you are not the intended recipient of this email or attachment you must
take no action based on it nor must you copy and show it to anyone else.
Please inform the sender if you have received this email in error

Vibas Ltd

**Comment by pedrobaeza** [comment]
And what is the error?

**Comment by sync700uk** [comment]
Hi
 Error report copied below :

Error:
Odoo Server Error

Traceback (most recent call last):
 * File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/http.py",
line 654, in _handle_exception*
*    return super(JsonRequest, self)._handle_exception(exception)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/http.py",
line 312, in _handle_exception*
*    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/tools/pycompat.py",
line 87, in reraise*
*    raise value*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/http.py",
line 696, in dispatch*
*    result = self._call_function(**self.params)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/http.py",
line 344, in _call_function*
*    return checked_call(self.db, *args, **kwargs)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/service/model.py",
line 97, in wrapper*
*    return f(dbname, *args, **kwargs)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/http.py",
line 337, in checked_call*
*    result = self.endpoint(*a, **kw)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/http.py",
line 939, in __call__*
*    return self.method(*args, **kw)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/http.py",
line 517, in response_wrap*
*    response = f(*args, **kw)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/addons/web/controllers/main.py",
line 966, in call_button*
*    action = self._call_kw(model, method, args, {})*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/addons/web/controllers/main.py",
line 954, in _call_kw*
*    return call_kw(request.env[model], method, args, kwargs)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/api.py",
line 749, in call_kw*
*    return _call_kw_multi(method, model, args, kwargs)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/api.py",
line 736, in _call_kw_multi*
*    result = method(recs, *args, **kwargs)*
*  File "<decorator-gen-61>", line 2, in button_immediate_install*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/addons/base/models/ir_module.py",
line 71, in check_and_log*
*    return method(self, *args, **kwargs)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/addons/base/models/ir_module.py",
line 442, in button_immediate_install*
*    return self._button_immediate_function(type(self).button_install)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/addons/base/models/ir_module.py",
line 535, in _button_immediate_function*
*    modules.registry.Registry.new(self._cr.dbname, update_module=True)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/modules/registry.py",
line 86, in new*
*    odoo.modules.load_modules(registry._db, force_demo, status,
update_module)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/modules/loading.py",
line 423, in load_modules*
*    loaded_modules, update_module, models_to_check)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/modules/loading.py",
line 315, in load_marked_modules*
*    perform_checks=perform_checks, models_to_check=models_to_check*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/modules/loading.py",
line 181, in load_module_graph*
*    load_openerp_module(package.name <http://package.name>)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/modules/module.py",
line 368, in load_openerp_module*
*    __import__('odoo.addons.' + module_name)*
*  File
"/opt/bitnami/apps/odoo/lib/odoo-12.0.post20181218-py3.7.egg/odoo/modules/module.py",
line 61, in load_module*
*    f, path, (_suffix, _mode, type_) = imp.find_module(addon_name,
ad_paths)*
*  File "/opt/bitnami/python/lib/python3.7/imp.py", line 296, in
find_module*
*    raise ImportError(_ERR_MSG.format(name), name=name)*
ImportError: No module named 'crm_phonecall-12'
No such module by that name

Adrian Maudsley, MAAT

This email is strictly confidential and for the intended recipients only.
If you are not the intended recipient of this email or attachment you must
take no action based on it nor must you copy and show it to anyone else.
Please inform the sender if you have received this email in error

Vibas Ltd

**Comment by pedrobaeza** [comment]
How are you installing it? Module name is not `crm_phonecall-12`, but `crm_phonecall`

**Comment by sync700uk** [comment]
Hi

Unzipped the package. Transferred "as is" to the server Odoo add-on folder
and update app list in developer mode

Adrian Maudsley, MAAT

This email is strictly confidential and for the intended recipients only.
If you are not the intended recipient of this email or attachment you must
take no action based on it nor must you copy and show it to anyone else.
Please inform the sender if you have received this email in error

Vibas Ltd

**Comment by pedrobaeza** [comment]
Then your method is incorrect. You have to respect the module name in the folder.
