### ISSUE TITLE
Question Performance after install of mass_mailing_partner

### ISSUE THREAD

**Issue by jbgraffiti** [OCA/crm#276]
Hello. So it's been a couple of days since installing the module on our sandbox

We have about 10000 partner records and I have noticed that certain periods the server slows down a lot - response times of page refreshes both front end and back end are increased to 20- 30 seconds.

I have deleted spare databases and gone from a T2.small to T2.medium on aws and still get the same issue. it seems to happen every 4 hours.

Is there something like a cron job that works in the background and checks for changes in the database between statistics / partner / mass mailing?

With that number of records, do I need to increase the number of workers? 

thanks
Jon

**Comment by pedrobaeza** [comment]
The module you mention is not from this repository, but OCA/social. Please put the issue there and indicate the Odoo version.
