### ISSUE TITLE
Example Sales Team name is missing a space

### ISSUE THREAD

**Issue by sharpelectronics** [OCA/crm#282]
This is a training database on Odoo 12.0e (Enterprise Edition). Then if you go to CRM - Configuration - Sales Teams - Create, in the field for Sales Teams Name, there is a grey sales team name example that says "Salesteam name...". I believe that this should read" Sales Team name..." 

![Annotation 2019-06-11 113648](https://user-images.githubusercontent.com/51717377/59293883-6e201200-8c3d-11e9-9dd3-8209928509af.png)

**Comment by pedrobaeza** [comment]
What you are talking about is Odoo standard, not any module in this repository. Go to odoo/odoo.
