### ISSUE TITLE
Pre-commit run -a fail

### ISSUE THREAD

**Issue by flachica** [OCA/crm#310]
pre-commit run -a fail saying `$HOME/.cache/pre-commit/reposly06dak/py_env-python3/bin/python: No module named pip`

If I copy pre-commit configuration files from management-system all run correctly. With OCA/knowledge is the same. How I can comunicate/solve this?

**Comment by pedrobaeza** [comment]
The problem is in your local. You don't have pip available. Maybe `sudo apt-get install python3-setuptools` fix it if you are in Ubuntu 18.04. Any way, the problem is outside this scope.

**Comment by flachica** [comment]
Thanks for the hint despite leaving the scope of the project. I had disparate versions of python 3 installed, I uninstalled them and left only one. Also, I went through all the symbolic links and there was something wrong. Let's continue contributing our grain of sand.
