### ISSUE TITLE
[12.] crm_phonecall_planner: improve inheritance crm_phonecall 

### ISSUE THREAD

**Issue by skeller1** [OCA/crm#332]
Hi,
at the moment it's not possible to use crm_phonecall, crm_phonecall_summary_predefined and crm_phonecall_planner at the same time in Odoo 12.0 without problems.

In PR #327 inheritance of crm_phonecall 13.0 has been improved.
Is this breaking change also allowed in V12? 

I would like to do some PR's for all the 3 mentioned addons in 12.0.

**Comment by pedrobaeza** [comment]
Which kind of breaking changes?

**Comment by skeller1** [comment]
Like in the pull request #327 changing  def schedule_another_phonecall()
Thank you

**Comment by pedrobaeza** [comment]
Adding a hook seems something feasible.

**Comment by skeller1** [comment]
I willl prepare the PR's

Thank you
