### ISSUE TITLE
Error during installation of crm_phonecall

### ISSUE THREAD

**Issue by rjay1018** [OCA/crm#340]
![image](https://user-images.githubusercontent.com/5526244/85260955-15b16080-b49e-11ea-96f9-e060bdb9a8a8.png)

**Comment by pedrobaeza** [comment]
You should have an altered Python environment, as the multi decorator is there:

https://github.com/odoo/odoo/blob/39c9ac02d42a9280caf41770efd2f91d096b52cf/odoo/api.py#L335

Maybe you are using Odoo v13.

**Comment by rjay1018** [comment]
okay my bad, ill go check it. thanks @pedrobaeza
