### ISSUE TITLE
[12.0] [crm_claim] Sale_orders link to claim_id and auto-invoice stock_picking to out_refund invoices?

### ISSUE THREAD

**Issue by victoralmau** [OCA/crm#344]
There are 2 ideas that may be useful:

- To the sale_orders add a claim_id field related to crm_claim, in such a way that by means of a button inside each crm_claim, orders linked to that claim could be created. Also, there would be a different numbering sequence for these orders.

- If we add a field in the crm_claim_category of auto-invoice, it could be done that for each incoming stock_picking (return) that is Done, it looks for the outgoing stock_picking, the sale_order, the invoice that has been created and from that invoice, create an out_refund invoke with the lines and quantities of the products that have been received in the stock_picking (as long as there is NO crm_claim linked to the sale_order with the type auto-invoice).
Note: The auto-invoice type in the crm_claim_category is necessary because for example for claims that are the fault of the transport, even if the products return, a corrective invoice should NOT be generated.

Currently we use these 2 things and they are useful to us, but we wanted to know if there is something similar and / or if it would be interesting to add it to the community.

**Comment by pedrobaeza** [comment]
We have abandoned crm_claim in favor of a more complete RMA management in https://github.com/OCA/rma

**Comment by victoralmau** [comment]
Ok, thank you very much, I am going to review in detail the new RMA system and try to change it to the one currently used (crm_claim) adjusting any other dependencies (such as auto-invoicing merchandise entries-returns- if those addons do not have it already developed)

**Comment by victoralmau** [comment]
Ok, thank you very much, looking at everything VERY in detail I think it has almost everything that we are currently using with crm_claim so we will move on to using it
