### ISSUE TITLE
crm_lead_product if more than 1 product added to lead, the result on analysis (cr.product.report) is corrupted

### ISSUE THREAD

**Issue by farazbdm** [OCA/crm#346]
![image](https://user-images.githubusercontent.com/10349579/87852449-22956880-c913-11ea-8e54-16a91e239668.png)
![image](https://user-images.githubusercontent.com/10349579/87852456-3345de80-c913-11ea-87bb-5217707817c2.png)

**Comment by farazbdm** [comment]
maybe its version issue i am installing on odoo10 and this module is for v11, but can please some1 assist or hint on the issue.

**Comment by farazbdm** [comment]
@pedrobaeza i will be thankful

**Comment by pedrobaeza** [comment]
It's something expected that the module for a version doesn't work properly into another version, so closing this. Please use the proper version for the module.
