### ISSUE TITLE
The crm_lead_vat's description could be more precise

### ISSUE THREAD

**Issue by alexandreduf** [OCA/crm#354]
Hi,

I'm referring to this module : https://github.com/OCA/crm/tree/13.0/crm_lead_vat

The description says "This module was written to extend the functionality of CRM leads to support setting the VAT."

I would detail what "VAT" means. I guess it's "Value added tax".
Writing "VAT (value added tax)" would be easier for people (who come from all over the world and speak multiple languages) to understand.

Thanks for your great work!

**Comment by pedrobaeza** [comment]
It's VAT identification number (https://en.wikipedia.org/wiki/VAT_identification_number), and it's usually called only as VAT in lot of places. Anyway, please do a PR for improving the description with such long name:

https://odoo-community.org/page/Contribute

**Comment by alexandreduf** [comment]
Hi,

I'm sorry, but I was told elsewhere on Github that PR weren't to be used for such comments and that I should use "issues" instead. So I don't know where to post comments anymore.

Furthermore, I still think that adding 3 words to make it more clear would help (and it wouldn't cost much).
As a French speaker, I had to Google the expression and I found "value added tax" instead...

**Comment by pedrobaeza** [comment]
I told you about creating the PR adding that 3 words, but OK, I have done it: eecbb5a9b3bb3b775d4aa4685e44e4cd0f003544

**Comment by alexandreduf** [comment]
Oh sorry, I think I didn't understand what you meant.
Thanks for the help!
