### ISSUE TITLE
can't delete contact after install mass_mailing_partner

### ISSUE THREAD

**Issue by alanljj** [OCA/crm#50]
when I try to delete any contact, the error shows:

AccessError

No value found for res.partner(7143,).mass_mailing_contacts 

May I ask how to solve the problem? Thanks!

**Comment by pedrobaeza** [comment]
I think the problem is with _partner_relations_, not with this module. Do you have it installed?

**Comment by alanljj** [comment]
yes, I installed it. Thanks!

**Comment by pedrobaeza** [comment]
Then the correct issue is https://github.com/OCA/partner-contact/issues/154.
