### ISSUE TITLE
To Task or to Project?

### ISSUE THREAD

**Issue by euroblaze** [OCA/crm#534]
## Module
`crm_project`

## Describe the bug
The README.rst suggests that this module converts CRM opps to tasks.

> This module allows to convert leads/opportunities to tasks.

But the name of the module suggests that a new Project is created.
In addition, there is a [different module](https://github.com/OCA/crm/tree/15.0/crm_project_task) called `crm_project_task`, which seems to be dedicated to creating a Task.

## To Reproduce
**Affected versions**: 15 at least, maybe others.

1. Please visit https://github.com/OCA/crm/blob/15.0/crm_project/README.rst
2.
3.

**Expected behavior**

I am a functional consultant, hence unable to follow the code completely.
I want to understand the diff. between these 2 modules from the README files.

**Additional context**
..

**Comment by rafaelbn** [comment]
Hello @euroblaze ,

**You have all explained here**: https://github.com/OCA/crm/issues/481

And in Odoo 16 modules have been rename for better understanding

https://github.com/OCA/crm/tree/16.0/crm_lead_to_task
(This module allows to convert leads/opportunities to tasks.)

https://github.com/OCA/crm/tree/16.0/crm_project_task
(This module allow create task from leads/opportunities)

I guess issue and doubt is solved 😄
