### ISSUE TITLE
Error al instalar módulo mass_mailing_partner

### ISSUE THREAD

**Issue by CarlesAntoli** [OCA/crm#68]
Me muestra el siguiente error al instalar el módulo- "El(los) campo(s) `res_model, src_model` fallaron contra la restricci\xf3n: Nombre de modelo no v\xe1lido en la definici\xf3n de acci\xf3n." while parsing file:///D:/Biblioteca/Extra_Addons/base-crm-sale/mass_mailing_partner/wizard/partner_mail_list_wizard.xml:11, near
<act_window name="Add to mailing list" res_model="partner.mail.list.wizard" src_model="res.partner" view_mode="form" target="new" key2="client_action_multi" id="action_partner_mail_list"/>"

He cambiado la sintaxis en la línea 6 del archivo "partner_mail_list_wizard.xml" por res_model="partner.mail.list.wizard" src_model="res.partner" y he podido instalar el módulo correctamente. La versión de odoo es la 8.

El trozo de código es el siguiente:
<act_window name="Add to mailing list"
    res_model="partner.mail.list.wizard" src_model="res.partner"
    view_mode="form"
    target="new"
    key2="client_action_multi"
    id="action_partner_mail_list"/>

Saludos

**Comment by rafaelbn** [comment]
Hi @CarlesAntoli ,

I have tested in runbot with a base database http://3119831-8-0-482f9c.runbot2.odoo-community.org and it install properly.

This should be an issue of you local environment.

Thanks
Regards
