### ISSUE TITLE
Is Transifex working for this repository?

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/crm#82]
I can't find this project on Transifex.

**Comment by max3903** [comment]
Answer is no:
https://github.com/OCA/crm/blob/9.0/.travis.yml

https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L36

**Comment by ivantodorovich** [comment]
Thank you for your response.

Although it was a somewhat rhetorical question. I'm not familiar with Transifex and how to make it work. Not even sure if I have access rights to do so.

To make it work one should only add those `env:` lines to `.travis.yml`? If so, I'm willing to do so.

**Comment by max3903** [comment]
Transifex configuration is just about adding those lines:
https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L35
https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L36
https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L43
https://github.com/OCA/maintainer-quality-tools/blob/master/sample_files/.travis.yml#L56

Most complicated part is to generate the secure.
