### ISSUE TITLE
[8.0][lettermgmt] Module simplification

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/crm#83]
I intend to use lettermgmt in our own company, but I found the module to be too much complicated for our current needs.

I'm wondering if @hbrunn or @bwrsandman can throw some clarification on a few things. I intend to improve the readme once I get a full sense of the module, and to further develop it.
### Letter States / Workflow

_Draft -> Created -> Validated -> Sent_

What's the purpose of this workflow? Why having both Created and Validated?
### Fields clarification / Intention

What's the purpose of these fields? Can you provide examples?

**parent:** How can a letter be parent/child of another letter?
**thread / child_ids:** I take it it's related to parent.. but can't seem to find an use case.

**type**: What's the type of letter? Is it the courier / postal service used? (IE: "48hs delivery") Could it be the kind of envelope used?
**class:** ¿? Is this supposed to be like internal categories of letters? (IE: "Invoice", "Receipt".. )
**channel:** Courier / postal service? Internal office? (IE: "FedEx" or maybe an internal office: "Front Desk")

**rassigment_ids**: Purpose/Example use case?

**Letter Folders**: Is it for big companies with a lot of letter transit locations?

**Comment by max3903** [comment]
@bwrsandman worked on it for a large organization with a internal courrier service in charge of receiving and shipping letters and parcels internally and externally.

# Workflow

You can have people creating the letter and people verifying that the information entered in the system is the one on the letters/parcels.

# Fields

parent: You can have one incoming shipment spread out among many letters/boxes.

This is as much as I can remember about it. Maybe @plamarche have more information.

**Comment by ivantodorovich** [comment]
Thanks for the clarification! :+1: 

I'll wait for the others' response

**Comment by hbrunn** [comment]
I just ported what existed, and actually wrote a module that dumbs this down be removing all fields you ask about save for `class`, `channel` and `type`. About those, have a look at the demo data in https://github.com/OCA/crm/blob/8.0/lettermgmt/data/letter_demo.xml to confirm you're mostly right about their use.

**Comment by ivantodorovich** [comment]
Thank you @hbrunn !

That module you wrote, the one that dumbs this down, is it public?

I'd like to hear your thought and @bwrsandman's about splitting this module in a few: a simplified base + specific extensions. I'll gladly make that PR, but only with your approval.

**Comment by hbrunn** [comment]
the dumbing down module is not public, but only for the reason I figured it's not interesting for anyone. Your proposal sounds a lot better to me. @bwrsandman doesn't work on Odoo any more to my knowledge, so I'm not sure he's interested in being involved here

**Comment by hbrunn** [comment]
maybe for compatibility keep lettermgmt depending on letter_management, letter_managemet_channel, letter_management_etc?

**Comment by ivantodorovich** [comment]
That sounds good to me. 
Although I have to ask, is it a standard practice in these cases?
For how long should lettermgmt be supported?

**Comment by max3903** [comment]
@ivantodorovich It will be supported as long as there are people to support it for users who uses it.

**Comment by ivantodorovich** [comment]
@max3903 I don't think we are talking about the same thing. I meant that question in response to @hbrunn's idea.

**Comment by ivantodorovich** [comment]
Ok, so.. to sketch resulting modules:
- `letter_management`: The base module. As simple as possible. I'm thinking on supporting current 'classes' (Personal, Confidential, Classified) as 'tags' instead.
- `letter_management_channel`: Add support for letter channels (Post, FedEx, UPS)
- `letter_management_type`: Add support for letter types (Envelope, Parcel)
- `letter_management_folder`: Add support for letter folders (Still don't know use case)
- `letter_management_shipment`: Add support for letter parent / childs.
- `letter_management_validation_workflow`: Add support for validation workflow

What about `reassigment_ids`? I don't understand the usecase yet.

**Comment by ivantodorovich** [comment]
Maybe `channel`, `type` and `folder` can be unified in a single `letter_management_extended` module..

**Comment by hbrunn** [comment]
it's quite usual to do this when you do refactorings in a branch where the module potentially already is installed in the wild. If you plan to do the refactoring during your port to 9.0, we don't need it. An example is `base_contact` which we split up in 8.0 I think: https://github.com/OCA/partner-contact/tree/8.0/base_contact

There you also find examples for moving xmlids to the new modules which will be pulled as dependency in the migration script. In a nutshell: For existing modules, the change needs to be done in a way that pulling the new code and `--update=all` is enough for people with the original module from the branch installed.

**Comment by hbrunn** [comment]
or what comes to my mind only now: How about attaching the fields in question to groups and make a configuration page that allows users to turn on the fields? Then only the workflow would need its own module, the rest would live in the main module and being turned off by default.

**Comment by ivantodorovich** [comment]
I understand.

Using groups would work for the extended fields and shipments, indeed. 
I don't have much experience developing for the OCA, so I'll go whatever way you want!
Do do you think it's better to handle it using groups?

EDIT: Based on what they did on `base_contact`, it seems the way to go is having separate modules for the fields. (ie: `partner_contact_birthdate`, `partner_contact_in_several_companies`, `partner_contact_nationality`). 
Don't you think?

**Comment by ivantodorovich** [comment]
Taking from what they did on `base_contact`, it seems the way to go is having separate modules for the fields.

**Comment by hbrunn** [comment]
in the case of `base_contact`, I think it's a good thing to have separate modules because those fields have nothing in common at all. Here, we need the base module anyways because it's a dependency for all the +1field modules, and given the amount of fields, we'd have quite a proliferation of modules, which is why I think the groups are a better choice

**Comment by ivantodorovich** [comment]
After thinking it a bit more, I'm more inclined to this idea:
- Use group for `reassignments`
- Use group for `parent_id`, `child_ids`
- Use module for `letter_management_validation_workflow`

And for the rest of the fields, I'll just rearrange the view and move them into an "Other information" tab. leaving only the most common fields at the top of the form.

**Comment by pedrobaeza** [comment]
Closing as there's a PR now
