### ISSUE TITLE
Question about Mandatory Partner and Partner Tag in mailing list form

### ISSUE THREAD

**Issue by mamaf** [OCA/crm#86]
module: mass_mailing_partner
version: 8.0

This is just a question : I can't see the usfullness of Mandatory Partner and Partner Tag in mailing list form
Could you explain how i'ts used

Thanks in advance

**Comment by pedrobaeza** [comment]
Mandatory partner forces to have a partner on each mailing list contacts, and creates one if doesn't exist when creating new records. It's useful when you need to have a res.partner linked for all your data (there are lots of these situations).

Partner Tag indicates which tag would the created partner has.
